### ISSUE TITLE
Cross-reference docs to other extensions

### ISSUE THREAD

**Issue by rly** [nwb-extensions-test/ndx-template#1]
Currently, [intersphinx](http://www.sphinx-doc.org/en/master/usage/extensions/intersphinx.html) is used to create cross-references to other documentation, e.g. the [core schema](https://nwb-schema.readthedocs.io/en/latest/). However, this reference to the core is hard-coded in docs/source/conf.py:
```python
intersphinx_mapping = {'core': ('https://nwb-schema.readthedocs.io/en/latest/', None)}
```

Change this behavior to allow cross-reference to docs of other extensions if the current extension uses other extensions.

Namespace YAML files will have to include an (optional) URL to the documentation of the included neurodatatypes:
```yaml
namespaces:
- author: Ben Dichter
  contact: example@example.com
  doc: ecog extensions
  name: ecog
  schema:
  - namespace: core
  - neurodata_types:
    - NWBDataInterface
    - Subject
  - documentation: https://nwb-schema.readthedocs.io/en/latest/
  - source: ecog.extensions.yaml
  version: 1.2.1
```

This will also require a change to `NWBNamespaceBuilder` in PyNWB and `NamespaceBuilder` in HDMF:
```python
ns_builder.add_spec(ext_path, neurodata_type, doc_url)
```

Useful refs:
https://stackoverflow.com/questions/30939867/how-to-properly-write-cross-references-to-external-documentation-with-intersphin
